// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_pn5ubZFiyF2RBSrEi25wrUQa3zisf8Y',
    appId: '1:635871222227:web:your_web_app_id', // You'll need to get this from Firebase Console
    messagingSenderId: '635871222227',
    projectId: 'friendly-hangar-410917',
    authDomain: 'friendly-hangar-410917.firebaseapp.com',
    storageBucket: 'friendly-hangar-410917.appspot.com',
    measurementId: 'G-MEASUREMENT_ID', // You'll need to get this from Firebase Console
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_pn5ubZFiyF2RBSrEi25wrUQa3zisf8Y',
    appId: '1:635871222227:android:2396f4f1955078d8c6f726',
    messagingSenderId: '635871222227',
    projectId: 'friendly-hangar-410917',
    storageBucket: 'friendly-hangar-410917.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_pn5ubZFiyF2RBSrEi25wrUQa3zisf8Y',
    appId: '1:635871222227:ios:your_ios_app_id', // You'll need to get this from your iOS app in Firebase Console
    messagingSenderId: '635871222227',
    projectId: 'friendly-hangar-410917',
    storageBucket: 'friendly-hangar-410917.appspot.com',
    iosBundleId: 'com.example.studentReminderApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDemo_macOS_Key_Replace_With_Actual',
    appId: '1:123456789:ios:demo_app_id',
    messagingSenderId: '123456789',
    projectId: 'student-reminder-demo',
    storageBucket: 'student-reminder-demo.appspot.com',
    iosBundleId: 'com.example.studentReminderApp',
  );
}